### ISSUE TITLE
Move to AFNetworking 2 or NSURLSession

### ISSUE THREAD

**Issue by pkluz** [octokit/octokit.objc#181]
As @jspahrsummers requested, here's why I think we should:
Using Octokit is difficult when there's other libs using AFNetworking 2.

**Comment by pietbrauer** [comment]
Has anyone tried yet? I made the migration for https://github.com/xing/XNGAPIClient/pull/46 and it wasn't that hard after 3 attempts.

**Comment by joshaber** [comment]
We don't do anything particularly complex. I wonder if we might as well move to `NSURLSession`.

**Comment by jspahrsummers** [comment]
:+1: for `NSURLSession`.

**Comment by pietbrauer** [comment]
Shouldn't the issue be renamend then? :wink:

**Comment by joshaber** [comment]
I guess it's worthwhile noting that with AFNetworking 2 we can support 10.8, while `NSURLSession` is 10.9+.

**Comment by jspahrsummers** [comment]
> `NSURLSession` is 10.9+.

I have no problem with that.

**Comment by jspahrsummers** [comment]
Note that AFNetworking 2.5.1 has [a MITM vulnerability](http://blog.mindedsecurity.com/2015/03/ssl-mitm-attack-in-afnetworking-251-do.html?m=1) and should not currently be used.

**Comment by pietbrauer** [comment]
[AFNetworking 2.5.2 was released 9 hours ago](https://github.com/AFNetworking/AFNetworking/releases/tag/2.5.2) and should fix this issue.

**Comment by andrewjburnett** [comment]
Sorry to intrude but, if you are considering moving to either NSURLSession or AFNetworking 2, how do you overcome the issue of not being able to batch/enqueue requests efficiently? (because of the fact that NSURLSessionDataTasks are not operations). I've seen discussions of this all over but none with a convincing answer. The majority of responders simply encourage using AFHTTPOperationManager. However, I'm not terribly fond of this idea - from what I understand it's "the old way" of doing things. 
Again, sorry to bother you; but, the code for Octokit has been enlightening, as has the majority of material open-sourced from your team. I was simply hoping you may be able to shed knowledge on this dilemma.

**Comment by joshaber** [comment]
@andrewjburnett I don't think anyone's done any serious work on this so I doubt we have an answer or even understanding of the problem yet :dizzy_face:

**Comment by johndpope** [comment]
This is causing too much pain to use this library amongst other afnetworking 2 libraries.

**Comment by joshaber** [comment]
Pull requests welcome :smiley_cat:

**Comment by johndpope** [comment]
Hi Josh, I abandoned this repo in favour of the simpler - but just as powerful  slightly out of date UAGithubEngine https://github.com/owainhunt/UAGithubEngine/pull/37
